name: Test

on:
  push:
    paths:
      - '.github/workflows/test.yml'
      - '**/*.swift'
      - 'Sources/Clibsodium/**/*.c'
      - 'Sources/Clibsodium/**/*.h'
      - 'Sources/Clibsodium/**/*.S'
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - '**/*.swift'
      - 'Sources/Clibsodium/**/*.c'
      - 'Sources/Clibsodium/**/*.h'
      - 'Sources/Clibsodium/**/*.S'

jobs:
  swift-test:
    strategy:
      fail-fast: false
      matrix:
        operating-system: ["macos-13", "macos-14", "ubuntu-20.04", "ubuntu-22.04", "ubuntu-24.04"]
        swift-version: ["5.10.1"]
        include:
          - operating-system: windows-2019
            experimental: true
          - operating-system: windows-2022
            experimental: true
    runs-on: ${{ matrix.operating-system }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: Package resolve
        run: swift package resolve
      - name: Build
        run: |
          if [ -z "$RUNNER_DEBUG" ]; then
            swift build
          else
            swift build -v
          fi
      - name: Run tests
        run: |
          if [ -z "$RUNNER_DEBUG" ]; then
            swift test
          else
            swift test -v
          fi
